# Site settings
title: trnbtl
email: trnbtl@posteo.de
author: Daniel Kwittung
description: Welcomepage for the trnbtl community
url: trnbtl.githup.io

# Build settings
permalink: :/

# Social icons
show_social_icons: false

exclude: [/backup]
